import type { NextConfig } from "next";

// In dev, run Velite in watch mode so content edits hot-reload.
// For `build`, content is generated by the `velite` step in the build script
// (running it here races webpack and can wipe .velite mid-compile).
const isDev = process.argv.includes("dev");
if (isDev && !process.env.VELITE_STARTED) {
  process.env.VELITE_STARTED = "1";
  import("velite").then(({ build }) => build({ watch: true, clean: false }));
}

/**
 * Content-Security-Policy — shipped as Report-Only first (observe, don't break), to be
 * promoted to enforced (`Content-Security-Policy`) once a live check shows zero
 * violations. Scoped to the site's REAL surfaces (all verified against the code):
 *  - connect-src: 'self' covers every /api/* route (chat, tts, transcribe — Bedrock/
 *    Polly/Transcribe are called SERVER-side, so the browser never connects to AWS).
 *    Vercel analytics/insights endpoints added for the injected beacons.
 *    wss://speech.googleapis.com + wss://speech.platform.bing.com: browser Web Speech
 *    API (SpeechRecognition) opens a cross-origin WebSocket on Chrome/Edge respectively;
 *    subject to connect-src since Chrome 63 — without these two, the STT loop fails with
 *    network error on every attempt and voice is permanently broken in production.
 *    https://www.gstatic.com: Chrome's online SpeechSynthesis voices stream from here.
 *  - script/style 'unsafe-inline': Next inline bootstrap + the inlineCss experiment +
 *    R3F/Vercel inline. (No auth/secrets on this site, so the residual XSS surface is
 *    low; rehype-sanitize + skipHtml already neutralize chat markdown.)
 *  - img/media 'self' data: blob:: WebGL textures (data:) and the Polly <audio> blob:
 *    URL (URL.createObjectURL in use-speech-synthesis.ts).
 *  - frame-ancestors 'none': clickjacking defense (pairs with X-Frame-Options: DENY).
 */
const csp = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
  "script-src 'self' 'unsafe-inline' https://va.vercel-scripts.com https://vercel.live",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: https://img.shields.io",
  "media-src 'self' blob:",
  "font-src 'self' data:",
  // wss://speech.googleapis.com — Chrome/Chromium-based Edge Web Speech API (SpeechRecognition
  // opens a WebSocket to Google's cloud; subject to connect-src in Chrome 63+). Without this,
  // every recognition attempt fails with onerror.error="network", sending the voice loop to
  // "paused" immediately. Safari uses on-device processing (no external connect); Firefox
  // disables the API by default. The Playwright zero-violation audit never exercised live mic
  // input, so this was invisible until the CSP was enforced in production.
  // wss://speech.platform.bing.com — Edge on Windows uses Microsoft's speech service instead
  // of Google's; same WebSocket model, different host.
  // https://www.gstatic.com — Chrome's browser SpeechSynthesis online voices (e.g. "Google US
  // English") stream from gstatic. Without this they fall back to local voices (lower quality
  // but non-breaking); included here so neural voices work in talk mode.
  "connect-src 'self' https://*.vercel-insights.com https://vitals.vercel-insights.com https://va.vercel-scripts.com wss://speech.googleapis.com wss://speech.platform.bing.com https://www.gstatic.com",
  "worker-src 'self' blob:",
  "manifest-src 'self'",
  "upgrade-insecure-requests",
].join("; ");

// Static security headers applied to every route. HSTS is already set by Vercel's
// platform default, so it is intentionally omitted here (avoids a weaker duplicate).
const securityHeaders = [
  { key: "X-Frame-Options", value: "DENY" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  // Voice requests the mic — scope it to same-origin and deny camera/geo/etc.
  { key: "Permissions-Policy", value: "microphone=(self), camera=(), geolocation=(), browsing-topics=()" },
  // ENFORCED. Shipped Report-Only in v1.4.0; a live Playwright sweep across all four
  // views (incl. the WebGL Play view) logged ZERO violations, and a per-directive
  // audit against the real resource loads (scripts/styles/fonts/img/media/connect/
  // worker — including the Polly-audio blob: and AWS paths the sweep didn't exercise)
  // confirmed every browser-loadable resource is covered. The policy string is
  // unchanged from the Report-Only version — only the header key flips to enforce, so
  // the proven-safe baseline is exactly what's now blocking. `upgrade-insecure-requests`
  // is retained (it becomes meaningful once enforced). `'unsafe-inline'` on script/
  // style is intentional + unavoidable (Next inline bootstrap + inlineCss + Motion
  // runtime style attributes, which nonces can't cover) — accepted on an auth-less site.
  { key: "Content-Security-Policy", value: csp },
];

const nextConfig: NextConfig = {
  // Pin the workspace root to this project (multiple lockfiles exist on the machine).
  turbopack: { root: __dirname },
  // Inline critical CSS into <head> to cut a render-blocking stylesheet request —
  // Tailwind v4 is the exact use case this flag targets. Kept only if a before/after
  // Lighthouse on the deployed URL shows an FCP/LCP win without a TTFB regression.
  experimental: {
    inlineCss: true,
    // View Transitions API — enables React 19's <ViewTransition> component and
    // directional slide animations on project card links via transitionTypes.
    viewTransition: true,
    // Partial Prerendering (PPR) — cacheComponents:true is the Next.js 16 stable API
    // for PPR. API routes legitimately keep `export const runtime = "nodejs"` (AWS SDK,
    // Google Cloud SDK, Redis, MCP server) — PPR operates at the page/component level,
    // not the API route level, so runtime declarations on API routes do not block it.
    cacheComponents: true,
  },
  images: {
    formats: ["image/avif", "image/webp"],
    remotePatterns: [
      // github-readme-stats removed: the /projects feed is now first-party
      // (src/lib/github.ts, server-fetched + ISR) — no external <img> embed.
      { protocol: "https", hostname: "img.shields.io" },
    ],
  },
  async headers() {
    return [{ source: "/:path*", headers: securityHeaders }];
  },
};

export default nextConfig;
