import type { NextConfig } from "next";

// In dev, run Velite in watch mode so content edits hot-reload.
// For `build`, content is generated by the `velite` step in the build script
// (running it here races webpack and can wipe .velite mid-compile).
const isDev = process.argv.includes("dev");
if (isDev && !process.env.VELITE_STARTED) {
  process.env.VELITE_STARTED = "1";
  import("velite").then(({ build }) => build({ watch: true, clean: false }));
}

const nextConfig: NextConfig = {
  // Pin the workspace root to this project (multiple lockfiles exist on the machine).
  turbopack: { root: __dirname },
  images: {
    formats: ["image/avif", "image/webp"],
    remotePatterns: [
      { protocol: "https", hostname: "github-readme-stats.vercel.app" },
      { protocol: "https", hostname: "img.shields.io" },
    ],
  },
};

export default nextConfig;
