"use client";

import { useEffect } from "react";
import { Section } from "@/components/ui/section";

// Pagefind UI is loaded from the static bundle generated by `pagefind` post-build.
// It self-initializes on mount by finding #pagefind-search in the DOM.
// The CSS is inlined below to avoid a separate stylesheet request.
declare global {
  interface Window {
    PagefindUI: new (opts: { element: string; showImages?: boolean; resetStyles?: boolean }) => void;
  }
}

export default function SearchPage() {
  useEffect(() => {
    async function init() {
      // Dynamically load Pagefind UI bundle (only exists after build).
      // @ts-expect-error — path resolves at runtime from public/pagefind/, not in TS source tree.
      const { PagefindUI } = await import("/pagefind/pagefind-ui.js");
      new PagefindUI({
        element: "#pagefind-search",
        showImages: false,
        resetStyles: true,
      });
    }
    init().catch(() => {}); // Graceful no-op in dev (bundle not yet generated)
  }, []);

  return (
    <main className="flex-1">
      <Section label="// search" title="Search" titleAs="h1">
        <p className="mb-8 text-fg-muted">
          Search across projects, work, articles, and notes.
        </p>
        {/* Pagefind UI mounts here. Styled via pagefind-ui.css injected below. */}
        <link rel="stylesheet" href="/pagefind/pagefind-ui.css" />
        <div id="pagefind-search" className="max-w-2xl" />
      </Section>
    </main>
  );
}
